GET http://localhost:3000

###

DELETE http://localhost:3001/persons/292855
###
POST  http://localhost:3001/persons/
content-type: application/json

    {
     "name": "gmer" ,
     "number":"87597597"
    }


 ###

 