GET http://localhost:3001
###

DELETE http://localhost:3001/persons/677622
###
POST  http://localhost:3001/persons/
content-type: application/json

    {
     "name": "gmer" ,
     "number":"87597597"
    }


 ###

 